service: serverless-basic-re

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  deploymentBucket:
    name: wp-lambda-bucket
    serverSideEncryption: AES256

functions:
  hello:
    handler: lib/js/src/Hello.handler
    events:
      - http:
          path: /hello
          method: get
          cors: true
  users:
    handler: lib/js/src/Github.usersHandler
    events:
      - http:
          path: /users
          method: get
          cors: true
  user:
    handler: lib/js/src/Github.userHandler
    events:
      - http:
          path: /users/{userId}
          method: get
          cors: true

custom:
  webpack:
    includeModules: true
    webpackConfig: ./webpack.config.js
    packager: "yarn"

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true
